steps:
  - id: "docker_build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us.gcr.io/$PROJECT_ID/cloudrunfastapi", "."]

  - id: "docker_push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "us.gcr.io/$PROJECT_ID/cloudrunfastapi"]

  - id: "cloud_run_deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "api-$BRANCH_NAME",
        "--image=us.gcr.io/$PROJECT_ID/cloudrunfastapi:latest",
        "--cpu=2",
        "--port=80",
        "--memory=2048Mi",
        "--timeout=600",
        "--concurrency=20",
        "--platform=managed",
        "--max-instances=1000",
        "--region=us-central1",
        "--allow-unauthenticated",
        "--revision-suffix=$SHORT_SHA",
        "--set-env-vars=PROJECT_ID=$PROJECT_ID,SHORT_SHA=$SHORT_SHA",
      ]
  # - id: "create google cloud infrastructure"
  #   name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   args:
  #     - sh
  #     - -c
  #     - |
  #       echo "create domain name mapping ..."
  #       gcloud beta run domain-mappings create \
  #           --domain $_MY_DOMAIN \
  #           --service api-master \
  #           --platform managed \
  #           --region us-central1 || true
  #       echo "create google cloud scheduler job ..."
  #       gcloud scheduler jobs create http ping \
  #           --schedule="* * * * *" \
  #           --uri="https://$_MY_DOMAIN/healthcheck" \
  #           --http-method=GET || true
  #       echo "create iam binding for pubsub ..."
  #       gcloud projects add-iam-policy-binding $PROJECT_ID \
  #           --member="serviceAccount:$_SERVICE_ACCOUNT_ADDRESS"\
  #           --role='roles/iam.serviceAccountTokenCreator'
  #       echo "creating topics and subscriptions ..."
  #       gcloud pubsub topics create apipub || true
  #       gcloud pubsub subscriptions create apisub \
  #           --topic apipub \
  #           --topic-project $PROJECT_ID \
  #           --push-endpoint https://$_MY_DOMAIN/pubsub/receive_message \
  #           --push-auth-service-account $_SERVICE_ACCOUNT_ADDRESS \
  #           --expiration-period=never || true
