apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: entro-prediction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: entro-prediction
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50